import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { AuthProvider } from "@/context/AuthContext";
import { TicketProvider } from "@/context/TicketContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ai-Ticket-Nextjs",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-screen h-screen m-0 p-0`}>
        <AuthProvider>
          <TicketProvider>
            <Navbar />
            <div className="mx-auto w-full text-2xl gap-2 mb-10">
              {children}
            </div>
          </TicketProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
